export const GET_SUBMIT_REQUEST = "GET_SUBMIT_REQUEST";
export const GET_SUBMIT_SUCCESS = "GET_SUBMIT_SUCCESS";
export const GET_SUBMIT_ERROR = "GET_SUBMIT_ERROR";

export const GET_DELETE_REQUEST = "GET_DELETE_REQUEST";
export const GET_DELETE_SUCCESS = "GET_DELETE_SUCCESS";
export const GET_DELETE_ERROR = "GET_DELETE_ERROR";

export const GET_FORM_CHECKED_REQUEST = "GET_FORM_CHECKED_REQUEST";
export const GET_FORM_CHECKED_SUCCESS = "GET_FORM_CHECKED_SUCCESS";
export const GET_FORM_CHECKED_ERROR = "GET_FORM_CHECKED_ERROR";

export const GET_FILTER_REQUEST = "GET_FILTER_REQUEST";
export const GET_FILTER_SUCCESS = "GET_FILTER_SUCCESS";
export const GET_FILTER_ERROR = "GET_FILTER_ERROR";

export const GET_FORM_EDIT_REQUEST = "GET_FORM_EDIT_REQUEST";
export const GET_FORM_EDIT_SUCCESS = "GET_FORM_EDIT_SUCCESS";
export const GET_FORM_EDIT_ERROR = "GET_FORM_EDIT_ERROR";

export const GET_FORM_UPDATE_REQUEST = "GET_FORM_UPDATE_REQUEST";
export const GET_FORM_UPDATE_SUCCESS = "GET_FORM_UPDATE_SUCCESS";
export const GET_FORM_UPDATE_ERROR = "GET_FORM_UPDATE_ERROR";

export const GET_CHANGE_EDIT_REQUEST = "GET_CHANGE_EDIT_REQUEST";
export const GET_CHANGE_EDIT_SUCCESS = "GET_CHANGE_EDIT_SUCCESS";
export const GET_CHANGE_EDIT_ERROR = "GET_CHANGE_EDIT_ERROR";

export const GET_FILTEREDTODO_REQUEST = "GET_FILTEREDTODO_REQUEST";
export const GET_FILTEREDTODO_SUCCESS = "GET_FILTEREDTODO_SUCCESS";
export const GET_FILTEREDTODO_ERROR = "GET_FILTEREDTODO_ERROR";
